@startuml

title __UTILS's Class Diagram__\n

  namespace com.annushkaproject.programmerscalculator {
    namespace utils {
      class com.annushkaproject.programmerscalculator.utils.InstanceStateUtil {
          {static} + restoreProgrammerSavedInstance()
          {static} + restoreSavedInstance()
          {static} + saveInstanceState()
          {static} + saveInstanceState()
      }
    }
  }
  

  namespace com.annushkaproject.programmerscalculator {
    namespace utils {
      class com.annushkaproject.programmerscalculator.utils.ProgrammerOperationsUtil {
          {static} + calculateWithData()
          {static} - addSubtract()
          {static} - and()
          {static} - changeSign()
          {static} - divide()
          {static} - lsh()
          {static} - mod()
          {static} - multiply()
          {static} - not()
          {static} - or()
          {static} - rsh()
          {static} - xor()
      }
    }
  }
  

  namespace com.annushkaproject.programmerscalculator {
    namespace utils {
      class com.annushkaproject.programmerscalculator.utils.SharedPreferencesUtil {
          {static} - PREF : String
          {static} - PREFERENCES_LOG_TAG : String
          {static} - THEME_SETTING_KEY : String
          {static} - lang_settings_key : String
          - preferences : SharedPreferences
          - preferencesEditor : Editor
          + SharedPreferencesUtil()
          + loadThemeSetting()
          + load_language_setting()
          + onPreferencesUpdated()
          + saveThemeSetting()
          + save_lang_setting()
      }
    }
  }
  

  namespace com.annushkaproject.programmerscalculator {
    namespace utils {
      class com.annushkaproject.programmerscalculator.utils.StandardOperationsUtil {
          {static} + SCALE : int
          {static} + calculatePercentForData()
          {static} + calculateResultForOneSidedOperator()
          {static} + calculateResultForTwoSidedOperator()
          {static} - calculateFactorial()
      }
    }
  }
  

  namespace com.annushkaproject.programmerscalculator {
    namespace utils {
      class com.annushkaproject.programmerscalculator.utils.c_nmbr_utils {
          {static} + dizit_names_array : String[]
          {static} + ples_value_sphiks : String[]
          {static} + heks_nmbr_string_to_vrdsstring()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
